# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-09 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20180809_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
